<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>keyEquivalent</key>
        <string>^~R</string>
        <key>uuid</key>
        <string>B214BF1E-DC3B-4898-8B43-F7D3F48147F1</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>name</key>
                <string>meta.section.rd</string>
                <key>beginCaptures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.function.rd</string>
                    </dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.section.rd</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.arguments.begin.rd</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>(\})</string>
                <key>endCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.arguments.end.rd</string>
                    </dict>
                </dict>
                <key>contentName</key>
                <string>entity.name.tag.rd</string>
                <key>begin</key>
                <string>((\\)(?:name|alias|docType|keyword|format|item|section))(\{)</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>$self</string>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>begin</key>
                <string>((\\)(?:title|description|references|source|details|value|seealso|arguments|concept|author))(\{)</string>
                <key>endCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.arguments.end.rd</string>
                    </dict>
                </dict>
                <key>beginCaptures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.function.rd</string>
                    </dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.section.rd</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.arguments.begin.rd</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>meta.section.rd</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>$self</string>
                    </dict>
                </array>
                <key>end</key>
                <string>(\})</string>
            </dict>
            <dict>
                <key>name</key>
                <string>meta.usage.rd</string>
                <key>beginCaptures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.function.rd</string>
                    </dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.usage.rd</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.arguments.begin.rd</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>(\})</string>
                <key>endCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.arguments.end.rd</string>
                    </dict>
                </dict>
                <key>contentName</key>
                <string>source.r.embedded</string>
                <key>begin</key>
                <string>((\\)(?:usage))(\{)(?:\n)?</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>source.r</string>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>name</key>
                <string>meta.examples.rd</string>
                <key>beginCaptures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.function.rd</string>
                    </dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.examples.rd</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.arguments.begin.rd</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>(\})</string>
                <key>endCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.arguments.end.rd</string>
                    </dict>
                </dict>
                <key>contentName</key>
                <string>source.r.embedded</string>
                <key>begin</key>
                <string>((\\)(?:examples))(\{)(?:\n)?</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>source.r</string>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>include</key>
                <string>text.tex.latex</string>
            </dict>
        </array>
        <key>name</key>
        <string>Rd (rmate)</string>
        <key>scopeName</key>
        <string>source.rd</string>
        <key>fileTypes</key>
        <array>
            <string>rd</string>
            <string>Rd</string>
        </array>
        <key>foldingStopMarker</key>
        <string>(^\s*\)|^\s*\}|\}\})</string>
        <key>foldingStartMarker</key>
        <string>\\\w*\{\s*$</string>
    </dict>
</plist>
